### ISSUE TITLE
Config specifies max_position_embeddings as 1024

### ISSUE THREAD

**Issue by JohnGiorgi** [allenai/PRIMER#9]
Hi!

I noticed that the [PRIMERA configs](https://huggingface.co/allenai/PRIMERA/blob/main/config.json#L72) specifies `max_position_embeddings: 1024`. Is this intentional? AFAICT the HuggingFace library treats this as the maximum position embedding size of the _encoder_, or `max_encoder_position_embeddings`, which for PRIMERA is `4096`.

 E.g. in their `run_summarization.py` script, they appear to treat `max_position_embeddings` as `max_encoder_position_embeddings` [as they compare it to the `max_source_length`](https://github.com/huggingface/transformers/blob/215e0681e4c3f6ade6e219d022a5e640b42fcb76/examples/pytorch/summarization/run_summarization.py#L407-L410).

So I am wondering if `max_position_embeddings` should be set to 4096 in the PRIMERA configs, else it causes problems when trying to use with existing HF example scripts.

**Comment by jayded** [comment]
I can confirm that this affects `run_summarization.py` and is inconsistent with the semantics of other Huggingface configs.

**Comment by JohnGiorgi** [comment]
Was able to address it temporarily by doing:

```python
from transformers import AutoConfig

config = AutoConfig.from_pretrained("allenai/PRIMERA")
config.max_position_embeddings = 4096
config.save_prerrained("allenai/PRIMERA-fixed")
```

and then passing `"allenai/PRIMERA-fixed"` to the `run_*.py` scripts via the `--config_name` flag.

**Comment by Wendy-Xiao** [comment]
Hi John and Jay,

Thanks for pointing out the issue. It is **not** intentional to set `max_position_embedding` to be `1024`, it's just set by default. 

I have not used `run_summarization.py` before, so I didn't know that in that script they treat `max_position_embedding` as the maximum position embedding size for the encoder, which is specified as `max_encoder_position_embeddings` in our case. 

I'll update it in the config files, to make it consistent with the script.

**Comment by JohnGiorgi** [comment]
Awesome, thank you @Wendy-Xiao!

**Comment by JohnGiorgi** [comment]
Hi @Wendy-Xiao I see [this is fixed for base PRIMERA model](https://huggingface.co/allenai/PRIMERA/commit/049540344dc8d48cde86f83b9a8fec366e865bab). Would you mind making the same change to the fine-tuned models? (e.g. multi-news, [multi-x-science](https://huggingface.co/allenai/PRIMERA-multixscience/tree/main), etc.).

**Comment by JohnGiorgi** [comment]
Closing this as it was addressed, thank you @Wendy-Xiao!
